- name: Ensure base directory exists
  file: path={{ root_ca_base_dir }} state=directory
- name: Check if root CA cert exists
  stat: path={{ root_ca_base_dir }}/ca.pem
  register: stat_result
- name: Create root CA csr
  template: src=root-ca-csr.json dest={{ root_ca_base_dir }}
- name: Create root CA cert
  shell: cfssl gencert -initca root-ca-csr.json | cfssljson -bare ca
  args:
    chdir: "{{ root_ca_base_dir }}"
  when: not stat_result.stat.exists
- name: Copy root CA cert to chain file
  copy:
    remote_src: yes
    src: "{{ root_ca_base_dir }}/ca.pem"
    dest: "{{ root_ca_base_dir }}/ca-chain.pem"
